### ISSUE TITLE
 'Series' object has no attribute 'centers'

### ISSUE THREAD

**Issue by keithbriggs** [astrodsg/latbin#10]
kbriggs:~> python try_latbin.py
Traceback (most recent call last):
  File "try_latbin.py", line 15, in <module>
    centers = h.centers()
  File "/usr/lib/python2.7/dist-packages/pandas/core/generic.py", line 1815, in **getattr**
    (type(self).**name**, name))
AttributeError: 'Series' object has no attribute 'centers'

**Comment by quidditymaster** [comment]
We have moved from using custom PointInformation objects to simply using pandas groupby objects in the histogram and bin methods because it is faster and more flexible.  Although it is not an exact replacement for the centers method of the PointInformation object I have found that a generally superior option is to simply take the mean of the actual data in each bin as the bin center. The code example in the readme.md file has been updated to reflect this new behavior.
